-- Créer les tables uniquement si elles n'existent pas déjà
CREATE TABLE IF NOT EXISTS ATTEMPTSTATUS (
   IDATTEMPTSTATUS INT NOT NULL COMMENT '',
   NOMBRE_ESSAIE_ATTPSTATUS INT COMMENT '',
   ERROR_CODE_ATTPSTATUS INT COMMENT '',
   DATE_TENTATIVEATTPSTATUS DATE COMMENT '',
   DETAILS_ATTPSTATUS TEXT COMMENT '',
   STATUT_ATTPSTATUS TEXT COMMENT '',
   DESCRIPTION_ATTPSTATUS TEXT COMMENT '',
   COMMENT_ATTPSTATUS TEXT COMMENT '',
   PRIMARY KEY (IDATTEMPTSTATUS)
);

CREATE TABLE IF NOT EXISTS REQSTATUS (
   IDREQSTATUS INT NOT NULL COMMENT '',
   PRIORITY TEXT COMMENT '',
   LIBELLE_REQSTATUS TEXT COMMENT '',
   PRIMARY KEY (IDREQSTATUS)
);

CREATE TABLE IF NOT EXISTS REQTYPE (
   IDREQTYPE BIGINT NOT NULL COMMENT '',
   ACTION_TYPE TEXT COMMENT '',
   SIM_TYPE INT COMMENT '',
   LIBELLE_REQTYPE TEXT COMMENT '',
   PRIMARY KEY (IDREQTYPE)
);

CREATE TABLE IF NOT EXISTS REQSIM (
   IDREQIM INT NOT NULL COMMENT '',
   IDREQSTATUS INT NOT NULL COMMENT '',
   IDREQTYPE BIGINT NOT NULL COMMENT '',
   CREATION INT COMMENT '',
   RESOLUTION_DATE DATETIME COMMENT '',
   DESCRIPTION_REQSIM TEXT COMMENT '',
   ADRESS_IP LONGBLOB COMMENT '',
   PRIMARY KEY (IDREQIM),
   CONSTRAINT FK_REQSIM_CATEGORIS_REQSTATU FOREIGN KEY (IDREQSTATUS)
      REFERENCES REQSTATUS (IDREQSTATUS) ON DELETE RESTRICT ON UPDATE RESTRICT,
   CONSTRAINT FK_REQSIM_REFERENCI_REQTYPE FOREIGN KEY (IDREQTYPE)
      REFERENCES REQTYPE (IDREQTYPE) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS SENDSTATUS (
   IDSENDSTATUT INT NOT NULL COMMENT '',
   DURATION_DESCRIPTION INT COMMENT '',
   DATE_TENTATIVE_ENVOIE TEXT COMMENT '',
   DETAILS_SENDSTATUT TEXT COMMENT '',
   STATUT_ENVOIE TEXT COMMENT '',
   COMMENT_SENDSTATUS TEXT COMMENT '',
   ERROR_CODE_SENDSTATUS INT COMMENT '',
   DESCRIPTION_SENDSTATUS TEXT COMMENT '',
   PRIMARY KEY (IDSENDSTATUT)
);

CREATE TABLE IF NOT EXISTS SENDATTEMPTRESULT (
   IDSENDATTEMPTRESULT INT NOT NULL COMMENT '',
   CONTENU_REPONSE TEXT COMMENT '',
   DATE_OF_SENDING_RESULT DATE COMMENT '',
   NOMBRE_TENTATIVE_ATTPRESULT TEXT COMMENT '',
   DETAILS_SENDATTPRESULT TEXT COMMENT '',
   ERROR_CODE_SENDATTPRESULT INT COMMENT '',
   PRIMARY KEY (IDSENDATTEMPTRESULT)
);

CREATE TABLE IF NOT EXISTS SENDATTEMPT (
   IDSENDATTEMPT INT NOT NULL COMMENT '',
   IDSENDSTATUT INT NOT NULL COMMENT '',
   IDSENDATTEMPTRESULT INT NOT NULL COMMENT '',
   RESPONSE_DATA TEXT COMMENT '',
   RESPONSE_TIME DATETIME COMMENT '',
   COMMENT_SENDATTEMPT TEXT COMMENT '',
   REPONSE_FOURNIE TEXT COMMENT '',
   PRIMARY KEY (IDSENDATTEMPT),
   CONSTRAINT FK_SENDATTE_AGREGER_SENDSTAT FOREIGN KEY (IDSENDSTATUT)
      REFERENCES SENDSTATUS (IDSENDSTATUT) ON DELETE RESTRICT ON UPDATE RESTRICT,
   CONSTRAINT FK_SENDATTE_GENERER_SENDATTE FOREIGN KEY (IDSENDATTEMPTRESULT)
      REFERENCES SENDATTEMPTRESULT (IDSENDATTEMPTRESULT) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS SENDRESULT (
   IDSENDRESULT INT NOT NULL COMMENT '',
   IDSENDATTEMPT INT NOT NULL COMMENT '',
   DATE_DEBUT_SENDRESULT DATE COMMENT '',
   DATE_FIN_SENRESULT DATE COMMENT '',
   DATE_OF_SENDING DATE COMMENT '',
   DETAILS_SENDRESULT TEXT COMMENT '',
   COMMENT_SENDRESULT TEXT COMMENT '',
   ERROR_CODE_SENDRESULT INT COMMENT '',
   NOMBRE_DE_TENTATIVE_SENDRESULT INT COMMENT '',
   PRIMARY KEY (IDSENDRESULT),
   CONSTRAINT FK_SENDRESU_LIER_SENDATTE FOREIGN KEY (IDSENDATTEMPT)
      REFERENCES SENDATTEMPT (IDSENDATTEMPT) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS SIM (
   IDSIM BIGINT NOT NULL COMMENT '',
   NUM_TEL INT COMMENT '',
   ICC_ID INT COMMENT '',
   IMSI INT COMMENT '',
   PUK INT COMMENT '',
   PIN INT COMMENT '',
   PRIMARY KEY (IDSIM)
);

CREATE TABLE IF NOT EXISTS TREATRESULT (
   IDTREATRESULT INT NOT NULL COMMENT '',
   IDATTEMPTSTATUS INT NOT NULL COMMENT '',
   RESPONSE_HISTORY TEXT COMMENT '',
   DATE_TENTATIVEATTPRESULT DATE COMMENT '',
   DETAILS_ATTPRESULT TEXT COMMENT '',
   RESULTAT_OBTENU_ATTPRESULT TEXT COMMENT '',
   COMMENT_ATTPRESULT TEXT COMMENT '',
   PRIMARY KEY (IDTREATRESULT),
   CONSTRAINT FK_TREATRES_TRANSMIS_ATTEMPTS FOREIGN KEY (IDATTEMPTSTATUS)
      REFERENCES ATTEMPTSTATUS (IDATTEMPTSTATUS) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS TREATATTEMPT (
   IDTREATRESULT INT NOT NULL COMMENT '',
   IDTREATATTEMPT INT NOT NULL COMMENT '',
   DATE_DEBUT DATE COMMENT '',
   DATE_FIN DATE COMMENT '',
   DESCRIPTION_TREATATTEMPT TEXT COMMENT '',
   RESPONSABLE TEXT COMMENT '',
   RESULTAT_TREATATTEMPT TEXT COMMENT '',
   ERROR_CODE_TREATATTEMPT INT COMMENT '',
   PRIMARY KEY (IDTREATRESULT, IDTREATATTEMPT),
   CONSTRAINT FK_TREATATT_TRAITE_TREATRES FOREIGN KEY (IDTREATRESULT)
      REFERENCES TREATRESULT (IDTREATRESULT) ON DELETE RESTRICT ON UPDATE RESTRICT
);
